"""updated models

Revision ID: 800a7e3523a7
Revises: 7c7ddb74186a
Create Date: 2024-03-04 23:40:55.917079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800a7e3523a7'
down_revision = '7c7ddb74186a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('favorite_book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_customers_favorite_book_id_books'), 'customers', 'books', ['favorite_book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_customers_favorite_book_id_books'), 'customers', type_='foreignkey')
    op.drop_column('customers', 'favorite_book_id')
    # ### end Alembic commands ###
