"""empty message

Revision ID: 80ef2309f741
Revises: d258597127ca
Create Date: 2024-03-03 20:40:05.706885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ef2309f741'
down_revision = 'd258597127ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
