"""updated app

Revision ID: cac5a11da027
Revises: ec036f92a4b1
Create Date: 2024-03-04 09:09:45.397675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac5a11da027'
down_revision = 'ec036f92a4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('username', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', '_password_hash')
    op.drop_column('customers', 'username')
    # ### end Alembic commands ###
